---
- stat: path={{ ansible_env.HOME }}/.local/bin/pip
  register: pip_is_installed

- stat: path={{ ansible_env.HOME }}/.local/bin/pip3
  register: pip3_is_installed

- block:

  - name: install python-dev
    become: yes
    package: name=python-dev state=present

  - name: download get-pip.py
    get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp

  - name: install pip
    command: "python /tmp/get-pip.py --user"

  - name: delete get-pip.py
    file: state=absent path=/tmp/get-pip.py

  when: pip_is_installed.stat.exists == False

- block:

  - name: install python3-dev
    become: yes
    package: name=python3-dev state=present

  - name: download get-pip.py
    get_url: url=https://bootstrap.pypa.io/3.2/get-pip.py  dest=/tmp/pip3.py

  - name: install pip3
    command: "python3 /tmp/pip3.py --user"

  - name: delete pip3.py
    file: state=absent path=/tmp/pip3.py

  when: pip3_is_installed.stat.exists == False

- name: installing pipenv
  shell: "{{ ansible_env.HOME }}/.local/bin/pip install --user pipenv"
