---
- name: Create i3 config directory
  file: path={{ i3_config_dir }} state=directory

- name: Install i3 and deps
  become: yes
  package: name={{ item }} state=latest
  with_items:
   - i3
   - i3lock
   - i3status

- name: Link i3 files
  file: src={{item}} dest={{ i3_config_dir }}/{{ item | basename }} state=link
  with_fileglob:
   - i3/*

- name: set up pulseaudio group memberships
  user:
    append: yes
    groups: audio
    user: "{{ lookup('env','USER')}}"
  become: yes

- name: create dunst config dir
  file: path="{{ ansible_env.HOME }}/.config/dunst" state=directory

- name: Link dunstc
  file: >
    src={{item}}
    dest="{{ ansible_env.HOME }}/.config/dunst/{{ item | basename }}"
    state=link
  with_fileglob:
    - dunstrc
