---
- name: use git-core ppa for latest git
  apt_repository: repo="ppa:git-core/ppa" state=present
  become: yes
  when: ansible_service_mgr == 'apt'

- name: git
  become: yes
  package:
    name: git
    state: latest
