---
- name: use git-core ppa for latest git
  apt_repository: repo="ppa:git-core/ppa" state=present
  become: yes

- name: git
  become: yes
  package:
    name: git
    state: latest

- name: Create git_templates/hooks dir
  file: path={{ ansible_env.HOME }}/.git_templates/hooks state=directory

- name: Link git template files
  file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.git_templates/hooks/{{ item | basename }}"
    state: link
  with_fileglob:
    - git_templates/hooks/*

- name: Link global gitignore
  file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item | basename }}"
    state: link
  with_fileglob:
    - gitignore

- git_config:
    name: init.templatedir
    scope: global
    value: ~/.git_templates

- git_config:
    name: alias.cleanup
    scope: global
    value: "!git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d"

- name: create .local/bin dir
  file: path={{ ansible_env.HOME }}/.local/bin/ state=directory

- name: install diff-so-fancy
  get_url:
    url=https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    dest=~/.local/bin/

- name: make diff-so-fancy executable
  file:
    path: ~/.local/bin/diff-so-fancy
    mode: a+x
    state: file

- git_config:
    name: core.pager
    scope: global
    value: diff-so-fancy | less --tabs=4 -RFX

- git_config:
    name: color.ui
    scope: global
    value: true

- git_config:
    name: color.diff-highlight.oldNormal
    scope: global
    value: "red bold"
- git_config:
    name: color.diff-highlight.oldHighlight
    scope: global
    value: "red bold 52"

- git_config:
    name: color.diff-highlight.newNormal
    scope: global
    value: "green bold"

- git_config:
    name: color.diff-highlight.newHighlight
    scope: global
    value: "green bold 22"

- git_config:
    name: color.diff.meta
    scope: global
    value: "yellow"
- git_config:
    name: color.diff.frag
    scope: global
    value: "magenta bold"
- git_config:
    name: color.diff.commit
    scope: global
    value: "yellow bold"
- git_config:
    name: color.diff.old
    scope: global
    value: "red bold"
- git_config:
    name: color.diff.new
    scope: global
    value: "green bold"
- git_config:
    name: color.diff.whitespace
    scope: global
    value: "red reverse"
