---
- name: git
  become: yes
  apt:
    name: git
    state: present

- name: Create git_templates dir
  shell: mkdir -p {{ ansible_env.HOME }}/.git_templates

- name: Link git template files
  file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.git_templates/{{ item | basename }}"
    state: link
  with_fileglob:
    - git_templates/*

- name: copy gitconfig
  copy: src={{ item }}/ dest={{ ansible_env.HOME }}/.git_config
  with_fileglob:
    - gitconfig
