---
- name: Create git_templates/hooks dir
  file: path={{ ansible_env.HOME }}/.git_templates/hooks state=directory

- name: Link git template files
  file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.git_templates/hooks/{{ item | basename }}"
    state: link
  with_fileglob:
    - git_templates/hooks/*
