---
- name: tmux
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - tmux

- name: Link .tmux.conf
  file: src={{item}} dest={{ ansible_env.HOME }}/.{{ item | basename }} state=link
  with_fileglob:
    - tmux.* 

- name: check to see if tpm is already installed
  command: "ls {{ ansible_env.HOME }}/.tmux/plugins/tpm"
  ignore_errors: true
  register: tpm_is_installed
  changed_when: false

- block:

  - name: ensure tpm dir
    file: path={{ ansible_env.HOME }}/.tmux/plugins/tpm state=directory

  - name: clone tpm
    shell: git clone https://github.com/tmux-plugins/tpm {{ ansible_env.HOME }}/.tmux/plugins/tpm

  when: tpm_is_installed.rc != 0
