---
- name: install urxvt
  become: yes
  package: name=rxvt-unicode-256color state=present

- name: Link urxvt files
  file: >
    src={{item}}
    dest={{ ansible_env.HOME }}/{{ item | basename }}
    state=link
  with_fileglob:
   - .*

- name: create urxvt plugin dir
  file: path="{{ ansible_env.HOME }}/.urxvt/ext/" state=directory
- name: link font-size script
  file: >
    src="{{ role_path }}/files/font-size"
    dest={{ ansible_env.HOME }}/.urxvt/ext/
    state=link
