---
- name: install urxvt
  become: yes
  package: name=rxvt-unicode-256color state=present

- name: Link urxvt files
  file: >
    src={{item}}
    dest={{ ansible_env.HOME }}/{{ item | basename }}
    state=link
  with_fileglob:
   - .*

- name: link urxvt plugins
  file: >
    src="{{ role_path }}/files/ext/"
    dest="{{ ansible_env.HOME }}/.urxvt/ext"
    state=link
    force=yes
