---
- name: install various tools
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - wget
    - build-essential
    - automake
    - autoconf
    - pkg-config
    - libssl-dev
    - curl
    - gdebi
    - filezilla
    - vagrant
    - virtualbox
    - thunar
    - chromium-browser
    - mousepad
    - aria2
    - feh
    - tidy
    - dropbox

- name: add apt-fast/stable repository
  apt_repository: repo="ppa:apt-fast/stable" state=present
  become: yes

- name: install apt-fast
  become: yes
  package: name=apt-fast state=latest

- name: install rofi
  become: yes
  package: name=rofi state=latest
- name: create rofi dir
  file: path="{{ ansible_env.HOME }}/.config/rofi/" state=directory
- name: link rofi config
  file: >
    src="{{ role_path }}/files/rofi.config"
    dest={{ ansible_env.HOME }}/.config/rofi/config
    state=link

- name: install autorandr
  become: yes
  package: name=autorandr state=latest

- name: install todotxt-machine
  shell: "{{ ansible_env.HOME }}/.local/bin/pip install --user --upgrade todotxt-machine"

- name: install parcellite
  become: yes
  package: name=parcellite state=latest
