---
- name: install various tools
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - wget
    - build-essential
    - automake
    - autoconf
    - pkg-config
    - libssl-dev
    - curl
    - gdebi
    - filezilla
    - vagrant
    - virtualbox
    - thunar
    - chromium-browser
    - mousepad
