---

# - name: add dropbox source
#   become: yes
#   shell: >
#     apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
#     sh -c 'echo "deb http://linux.dropbox.com/ubuntu/ xenial main" > /etc/apt/sources.list.d/dropbox.list'
#     apt update

- name: add apt-fast/stable repository
  apt_repository: repo="ppa:apt-fast/stable" state=present
  become: yes
- name: install apt-fast
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - aria2
    - apt-fast

- name: install various tools
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - wget
    - build-essential
    - automake
    - autoconf
    - pkg-config
    - libssl-dev
    - curl
    - gdebi
    - filezilla
    - vagrant
    - virtualbox
    - thunar
    - chromium-browser
    - mousepad
    - feh
    - tidy
    - dropbox
    - fasd
    - autorandr
    - parcellite
    - openvpn

- name: install rofi
  become: yes
  package: name=rofi state=latest
- name: create rofi dir
  file: path="{{ ansible_env.HOME }}/.config/rofi/" state=directory
- name: link rofi config
  file: >
    src="{{ role_path }}/files/rofi.config"
    dest={{ ansible_env.HOME }}/.config/rofi/config
    state=link

- name: install todotxt-machine
  shell: "{{ ansible_env.HOME }}/.local/bin/pip install --user --upgrade todotxt-machine"

- name: disable openvpn at boot
  become: yes
  shell: "update-rc.d openvpn disable"
