---
- name: check to see if php is already installed
  command: "php5.6 --version"
  ignore_errors: true
  register: php56_is_installed
  changed_when: false

- block:
  - name: Add co-installable PHP 5.6 to source list
    apt_repository: repo="ppa:ondrej/php" state=present
    become: yes
    when: ansible_service_mgr == 'apt'

  - name: Install PHP 5.6
    package: name={{item}} state=latest
    become: yes
    with_items:
      - php5.6
      - php5.6-common
      - php5.6-mysql
      - php5.6-mcrypt
      - php5.6-mbstring
      - php5.6-json
      - php5.6-curl
      - php5.6-gd
      - php5.6-intl
      - php5.6-cli
      - php5.6-xml
      - php5.6-bz2
      - mcrypt
      - openssl
      - php-imagick
      - php-memcached
      - php-redis
      - php-xdebug
      - php-zip
      - php-ast

  when: php56_is_installed.rc != 0
