---
- name: check to see if php is already installed
  command: "php7.2 --version"
  ignore_errors: true
  register: php72_is_installed
  changed_when: false

- block:
  - name: Add co-installable PHP 7.2 to source list
    apt_repository: repo="ppa:ondrej/php" state=present
    become: yes
    when: ansible_service_mgr == 'apt'

  - name: Install PHP 7.2
    package: name={{item}} state=latest
    become: yes
    with_items:
      - php7.2
      - php7.2-common
      - php7.2-mysql
      - php7.2-mcrypt
      - php7.2-mbstring
      - php7.2-json
      - php7.2-curl
      - php7.2-gd
      - php7.2-intl
      - php7.2-cli
      - php7.2-xml
      - php7.2-bz2
      - mcrypt
      - openssl
      - php-imagick
      - php-memcached
      - php-redis
      - php-xdebug
      - php-zip
      - php-ast

  when: php72_is_installed.rc != 0
