---

- name: Create colors dir
  file:
    path: "{{ neovim_config_dir }}/colors"
    state: directory

- name: Link colorschemes
  file:
    src: "{{ item }}"
    dest: "{{ neovim_config_dir }}/colors/{{ item | basename }}"
    state: link
  with_fileglob:
    - colors/*
