---
- name: pip2 | neovim
  shell: "{{ ansible_env.HOME }}/.local/bin/pip install --user --upgrade neovim"

- name: pip3 | neovim
  shell: "{{ ansible_env.HOME }}/.local/bin/pip3 install --user --upgrade neovim"

- name: neovim ppa
  become: yes
  apt_repository: repo='ppa:neovim-ppa/unstable' state=present

- name: install neovim
  become: yes
  package: name=neovim state={{ neovim_install_state }}

- name: setup | vim-plug directory
  file: path="{{ neovim_config_dir }}/autoload" state=directory

- name: install | vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    force: yes

- name: Link neovim dotfiles
  file:
    src: "{{ item }}"
    dest: "{{ neovim_config_dir }}/{{ item | basename }}"
    state: link
  with_fileglob:
    - conf/*

- name: Create ftplugin dir
  shell: mkdir -p {{ neovim_config_dir }}/ftplugin

- name: Link ftplugin files
  file:
    src: "{{ item }}"
    dest: "{{ neovim_config_dir }}/ftplugin/{{ item | basename }}"
    state: link
  with_fileglob:
    - ftplugin/*

- name: Create UltiSnips dir
  shell: mkdir -p {{ neovim_config_dir }}/UltiSnips

- name: Link UltiSnips snippets
  file:
    src: "{{ item }}"
    dest: "{{ neovim_config_dir }}/UltiSnips/{{ item | basename }}"
    state: link
  with_fileglob:
    - UltiSnips/*

- name: install | plugins
  command: "nvim +silent! +PlugInstall! +UpdateRemotePlugins! +qall!"
  ignore_errors: true
