---

- name: Check if last npm linter is installed
  shell: source ~/.zshrc && prettier --version executable=/bin/zsh
  ignore_errors: true
  register: last_npm_linter_check
  changed_when: false

- block:
  - name: installing node & npm
    shell: source ~/.zshrc && nvm install --lts executable=/bin/zsh

  - name: installing linters/tools via npm
    shell: >
      source ~/.zshrc &&
      npm install -g
      jsonlint fixjson markdownlint-cli instant-markdown-d serverless neovim
      stylelint write-good remark-lint tern eslint tern-lint typescript
      eslint-config-standard eslint-plugin-node eslint-plugin-promise
      eslint-plugin-standard javascript-typescript-langserver tslint htmllint
      csslint prettier
      executable=/bin/zsh
  when: last_npm_linter_check.rc != 0
