---

- name: setup | vim-plug directory
  file: path="{{ neovim_config_dir }}/autoload" state=directory

- name: install | vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_config_dir }}/autoload/plug.vim"
    force: yes
